services:
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass myredispassword

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redis-insight-data:/data

volumes:
  postgres-data:
  redis-data:
  redis-insight-data:
